### ISSUE TITLE
Uncaught SyntaxError: Unexpected identifier

### ISSUE THREAD

**Issue by krazzington** [dappuniversity/starter_kit#19]
If there's a level below beginner, that is I. I'm getting the above error when I try to start Node.js re: Greg's YT blockchain tutorial. 

The node.js that I'm running looks nothing look the one in the tutorials. My format looks more like notepad. No colours change when I type in commands like 
> code
> eth_swap

Any help is appreciated.

MK

**Comment by funkytaco** [comment]
It sounds like you have no idea what you are doing. Hire a developer or start with a reactjs bootcamp. You're confusing a text editor with a shell command prompt.
