### ISSUE TITLE
Can anybody help me ,I am trying to clone the git repository

### ISSUE THREAD

**Issue by AntonyKimani** [dappuniversity/starter_kit#21]
git : The term 'git' is not recognized as the name of a 
cmdlet, function, script file, or operable program. Check the 
spelling of the name, or if a path was included, verify that  
the path is correct and try again.
At line:1 char:1
+ git clone https://github.com/dappuniversity/starter_kit     
+ ~~~
    + CategoryInfo          : ObjectNotFound: (git:String) []  
   , CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

**Comment by bluebinge** [comment]
Im gitting same issue

**Comment by shijogeorge5638** [comment]
Install Git

**Comment by AntonyKimani** [comment]
thanks bro
